---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5jbi1zaGVuemhlbi5hbGl5dW5jcy5jb20iOnsidXNlcm5hbWUiOiJkb2NrZXJAMTY4ODY1NTI5MzQxNzk5OSIsInBhc3N3b3JkIjoiOTc4MTA5NzA5ZTEzYWUyYjdiYzE1MDIyIiwiYXV0aCI6IlpHOWphMlZ5UURFMk9EZzJOVFV5T1RNME1UYzVPVGs2T1RjNE1UQTVOekE1WlRFellXVXlZamRpWXpFMU1ESXkifX19
kind: Secret
metadata:
  name: aozhe-images
type: kubernetes.io/dockerconfigjson

---
apiVersion: v1
data:
  application.properties: |
    ### web
    server.servlet.context-path=/
    ### actuator
    management.health.mail.enabled=false
    ### xxl-job, datasource
    spring.datasource.url=jdbc:mysql://rm-wz98s458p2om7411n.mysql.rds.aliyuncs.com:3306/app_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    spring.datasource.username=root
    spring.datasource.password=test123456!@#$%
    ### datasource-pool
    spring.datasource.hikari.minimum-idle=10
    spring.datasource.hikari.maximum-pool-size=30
    ### xxl-job, email
    spring.mail.host=smtp.qq.com
    spring.mail.port=25
    spring.mail.username=xxx@qq.com
    spring.mail.from=xxx@qq.com
    spring.mail.password=xxx
    ### xxl-job, access token
    xxl.job.accessToken=
    ## xxl-job, triggerpool max size
    xxl.job.triggerpool.fast.max=200
    xxl.job.triggerpool.slow.max=100
    ### xxl-job, log retention days
    xxl.job.logretentiondays=10

kind: ConfigMap
metadata:
  name: app-job-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-job
  name: app-job
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: app-job
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-job
    spec:
      containers:
        - env:
            - name: OTHER_OPTS
              value: '-DSW_AGENT_NAME=tptest-app-job -DSW_AGENT_COLLECTOR_BACKEND_SERVICES=tracing-analysis-dc-sz-internal.aliyuncs.com:8000 -DSW_AGENT_AUTHENTICATION=gmktj5wvtb@6f9f9621157b703_gmktj5wvtb@53df7ad2afe8301 -javaagent:agent/skywalking-agent.jar'
          image: registry.cn-shenzhen.aliyuncs.com/cloudpivot/app-job:master
          imagePullPolicy: Always
          name: app-job
          resources:
            limits:
              cpu: '1'
              memory: 2048Mi
            requests:
              cpu: '1'
              memory: 2048Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data/cloudpivot/application.properties
              name: configmap-app-job-config
              subPath: application.properties
          readinessProbe: # Pod 准备服务健康检查设置
            httpGet:
              path: /actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: aozhe-images
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: configmap-app-job-config
          configMap:
            defaultMode: 420
            items:
              - key: application.properties
                path: application.properties
            name: app-job-config


---
apiVersion: v1
kind: Service
metadata:
  name: svc-app-job
spec:
  ports:
    - name: tp-port
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app-job



---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-spec: slb.s1.small
  name: svc-app-job-lb
spec:
  externalTrafficPolicy: Local
  ports:
    - name: svc-app-job-lb-port
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: app-job
  sessionAffinity: None
  type: LoadBalancer
